// Generated by CoffeeScript 2.3.2
(function() {
  var app;

  app = new Vue({
    el: "#app",
    data: {
      hours: 0,
      minutes: 0,
      seconds: 0,
      timer: void 0,
      works: false,
      loaded: false
    },
    methods: {
      stop: function() {
        this.works = false;
        clearTimeout(this.timer);
        window.navigator.vibrate([1000, 1000, 1000, 1000, 1000]);
        return alert('TIME IS OVER');
      },
      useme: function() {
        this.works = true;
        return this.timer = setInterval((() => {
          var ref, ref1;
          if (this.works) {
            if (((this.seconds === (ref1 = this.minutes) && ref1 === (ref = this.hours)) && ref === 0)) {
              return this.stop();
            } else {
              if (this.seconds > 0) {
                return this.seconds--;
              } else {
                if (this.minutes > 0) {
                  this.minutes--;
                  return this.seconds = 59;
                } else {
                  this.hours--;
                  this.minutes = 59;
                  return this.seconds = 59;
                }
              }
            }
          }
        }), 1000);
      }
    }
  });

}).call(this);
