// Generated by CoffeeScript 2.3.2
(function() {
  var app;

  app = new Vue({
    el: "#app",
    data: {
      loading: true
    },
    mounted: function() {
      return setTimeout((() => {
        return this.loading = false;
      }), 1500);
    }
  });

}).call(this);
